{
  "lr": 0.001,
  "wd": 5e-5,
  "epochs": 100,
  "tr_batch_size": 1024,
  "hidden_channels": [128, [256, 128, 64, 1]],
  "num_heads": 8,                                                                 
  "num_layers": 2,
  "num_neighbors": [256],
  
  "mlp_dropout" : 0.4,
  "mlp_lr": 0.005,
  "mlp_wd": 0.0001,

  "neg_sample_ratio": 100,
  "pos_weight": 100
  }